# Global Values
repoUrl: 'git@github.com:oukhay/eks-blueprints-add-ons.git'
targetRevision: main
region: ''
account: ''
clusterName: ''


# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: true
  createNamespace: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1